mkdir "Лабораторные"
mkdir "Лабораторные\Группа"
mkdir "Лабораторные\Группа\ФИО"
mkdir "Лабораторные\Группа\ФИО\Командная строка"
mkdir "Скрытая папка"
mkdir "Не скрытая папка"
mkdir "Лабораторные\Группа\ФИО\batch"
attrib +h "Скрытая папка"
xcopy /?
xcopy /? > "Не скрытая папка\copyhelp.txt"
xcopy "Не скрытая папка\copyhelp.txt" "Скрытая папка\copied_copyhelp.txt"
echo @echo off > "Лабораторные\Группа\ФИО\batch\open_report.bat"
echo start notepad "Скрытая папка\copied_copyhelp.txt" >> "Лабораторные\Группа\ФИО\batch\open_report.bat"
echo pause >> "Лабораторные\Группа\ФИО\batch\open_report.bat"